app:
  documan:  
    rabbitmq:
      connection:
        username: user
        password: user
        hostname: localhost
      queues:
        documan: hello.dev.queue
      exchanges: 
        intercom: intercom
      routingKeys:
        documanRequiredFiles: documan.required.files
